### ISSUE TITLE
Mysql schema location?

### ISSUE THREAD

**Issue by hajimurtaza** [SaiUpadhyayula/spring-reddit-clone#10]
Can you provide location for schema of database. In your website only diagram is there.

**Comment by SaiUpadhyayula** [comment]
You don't need schema file, make sure the database is created in mysql and then just update the application.properties with your local db credentials, start the application and Hibernate will automatically create the tables.

**Comment by hajimurtaza** [comment]
Yes , I had failed to annotate one of the classes , hence dependency injection was failing. Its working now. Thanks. You can close or delete this issue.
