### ISSUE TITLE
parser() method in jwts is deprecated

### ISSUE THREAD

**Issue by hajimurtaza** [SaiUpadhyayula/spring-reddit-clone#11]
Can you update `JwtProvider.java` file in security package since parser().setSigningKey() doesnt work anymore. Not able to find replacement  solution for that as well.

![image](https://user-images.githubusercontent.com/29270236/100139160-0b383000-2e5d-11eb-9bca-d12d440c51e4.png)

**Comment by fullslackdev** [comment]
The code in JwtProvider.java is incorrect yes, see https://github.com/SaiUpadhyayula/spring-reddit-clone/blob/master/src/main/java/com/programming/techie/springredditclone/security/JwtProvider.java#L69
You need to change this line and any other calls to the deprecated parser() method with `Jwts.parserBuilder().setSigningKey(getPublicKey()).build().parseClaimsJws(jwt);`.
The `parserBuilder().setSigningKey(getPublicKey()).build()` is the part that replaces the deprecated method call.

**Comment by SaiUpadhyayula** [comment]
I didn't find time to check it, I can check this weekend, meanwhile if you are interested, please feel free to raise a PR :)

**Comment by rohan2810** [comment]
Hi, I have raised a PR for the same.
Please check it out.

**Comment by SaiUpadhyayula** [comment]
Issue is fixed with this PR https://github.com/SaiUpadhyayula/spring-reddit-clone/pull/16
