### ISSUE TITLE
MAPSTRUCT NOT WORKING ON ECLIPSE COMMUNITY VERSION

### ISSUE THREAD

**Issue by naseerahmed587** [SaiUpadhyayula/spring-reddit-clone#12]
Sir i have done all hard work on map struct but its not working even i tried it without lombok on some other classes just to test it but its not working. kindly guide me or if u can share some videos for it please thanks so much

**Comment by SaiUpadhyayula** [comment]
hi, I believe you may have already solved this issue, unfortunately, I didn't work on Eclipse for the past 5 years, so I cannot give any guidance here.

The starting place is to search how to integrate Lombok and map struct in Eclipse.

If nothing works, you can give IntelliJ IDEA a try, it contains the community edition, if you are not comfortable with that then you can always create the mapping methods by hand.
