### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 

### ISSUE THREAD

**Issue by Nikhil-Wani** [SaiUpadhyayula/spring-reddit-clone#13]
Hello Sir,
   Sir I Follow all your tutorials and Instructions the program is running but whenever I post something Its shows on View post page but its not showing in User profile page.

![user-profile-page1](https://user-images.githubusercontent.com/65514201/104430243-6e685800-55ac-11eb-8795-4fb819c5872f.jpg)

can you please clarify these query.

**Comment by SaiUpadhyayula** [comment]
hi Nikhil, can you please send me the Github link for your code? hard to say what is going wrong without looking the code

**Comment by Nikhil-Wani** [comment]
Hello sir

Code:
	backend  https://github.com/Nikhil-Wani/Reddit-Clone-Spring-Backend
	frontend https://github.com/Nikhil-Wani/Reddit-Clone-Angular-Frontend

I'm Getting this Error
Error : Failed to load resource: the server responded with a status of 403 () :8080/api/posts/:1 

I'm Getting this msg on postman
{
    "timestamp": 1611069918445,
    "status": 403,
    "error": "Forbidden",
    "message": "Access Denied",
    "path": "/api/posts/by-user/Nik"
}
