### ISSUE TITLE
CommentMapper bean error during runtime

### ISSUE THREAD

**Issue by iamnav** [SaiUpadhyayula/spring-reddit-clone#2]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of constructor in com.programming.techie.springredditclone.service.CommentService required a bean of type 'com.programming.techie.springredditclone.mapper.CommentMapper' that could not be found.

Action:

Consider defining a bean of type 'com.programming.techie.springredditclone.mapper.CommentMapper' in your configuration.

*Edit: This error is appearing for every Mapper interface/abstract class

**Comment by SaiUpadhyayula** [comment]
Can you try to run the command mvn clean install and check again ?

At compile time a CommentMapperImpl class should be generated, if not it will throw this error.

Also make sure you have added mapstruct to the maven compiler plugin configuration.

**Comment by iamnav** [comment]
Hey,
Thanks for the quick response. That did the trick! also as I am using Eclipse, I had to do some preference settings bit differently than intelliJ
