### ISSUE TITLE
Maven clean install failed

### ISSUE THREAD

**Issue by nsridatta** [SaiUpadhyayula/spring-reddit-clone#20]
Compilation Errors:
cannot find symbol
  symbol:   static parserBuilder
  location: class io.jsonwebtoken.Jwts
/src/main/java/com/programming/techie/springredditclone/security/JwtProvider.java:[18,1]

After analyzing, I found that the below import in the JwtProvider Class is not recognizing
"import static io.jsonwebtoken.Jwts.parserBuilder;"

Although have used your same pom.xml file in my project.

Thanks

**Comment by Tarun-c** [comment]
Try to change the JSON web token version in the pom.xml file.

The same problem happened to me but when I change my JSON web token dependency version. Then It works fine.

### Reference 

<dependency>
    <groupId>io.jsonwebtoken</groupId>
    <artifactId>jjwt-api</artifactId>
    <version>0.11.2</version>
</dependency>
<hr>
<dependency>
    <groupId>io.jsonwebtoken</groupId>
    <artifactId>jjwt-impl</artifactId>
    <version>0.11.2</version>
    <scope>runtime</scope>
</dependency>
<hr>
<dependency>
    <groupId>io.jsonwebtoken</groupId>
    <artifactId>jjwt-jackson</artifactId> 
    <version>0.11.2</version>
    <scope>runtime</scope>
</dependency>
