### ISSUE TITLE
no need for a custom JWTFilter

### ISSUE THREAD

**Issue by Tandolf** [SaiUpadhyayula/spring-reddit-clone#22]
https://github.com/SaiUpadhyayula/spring-reddit-clone/blob/bdedc07f2ad419063f57fca9cc7827dce5efd96c/src/main/java/com/programming/techie/springredditclone/security/JwtAuthenticationFilter.java#L20

Spring security has full support for JWTs with a customizable filter implemented.

https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-architecture

**Comment by SaiUpadhyayula** [comment]
@Tandolf Thank you for taking the time to suggest the changes, I highly appreciate it. When I created this project (mainly for the tutorial) it was not planned to use OAuth2 Resource Server capabilities, that was the reason why I implemented this.

To include these changes I have to completely rewrite the authentication using Spring Security OAuth2, as the repo is created to back up the tutorial, I am planning to not do this.

**Comment by Tandolf** [comment]
Spring-security-oauth2 is a completly other project which is in maintnance mode (as in no updates are done).

what i am referring to is that since spring security 5 there has been full support for handling JWTs ars bearer tokens. But most tutorials (as well as this one) is still implementing tokens as if it was using Spring security 4.

so the emphesis what i am talking about is using spring security 5, and not spring-security-oauth2.

**Comment by SaiUpadhyayula** [comment]
Yes, I understood what you meant :). I did not mean the spring-security-oauth2 project itself, but the latest OAuth2 support for Spring Security. 

I was not aware that I can use the `spring-boot-starter-oauth2-resource-server` project without using an authorization server.

By having a look at the Spring Security Samples https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/jwt/login I understood that this is indeed possible.

**Comment by SaiUpadhyayula** [comment]
This issue is now resolved with this commit - https://github.com/SaiUpadhyayula/spring-reddit-clone/commit/66fe28499e3ba64439eb72ffceba059e69a81201
