### ISSUE TITLE
Spring already comes with Nimbus JWT library

### ISSUE THREAD

**Issue by Tandolf** [SaiUpadhyayula/spring-reddit-clone#23]
https://github.com/SaiUpadhyayula/spring-reddit-clone/blob/bdedc07f2ad419063f57fca9cc7827dce5efd96c/pom.xml#L67

There is no need for an "extra" JWT library, when Nimbus JWT library is already included in spring security.

https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-decoder-bean

**Comment by SaiUpadhyayula** [comment]
The issue is addressed as per this commit - https://github.com/SaiUpadhyayula/spring-reddit-clone/commit/66fe28499e3ba64439eb72ffceba059e69a81201

Thanks for creating the issue
