### ISSUE TITLE
Login Authentication

### ISSUE THREAD

**Issue by Gideon7** [SaiUpadhyayula/spring-reddit-clone#26]
On login, after inputting correct username and password, login response gives bad credentials.

from this code line:
Authentication authenticate = authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(loginRequest.getUsername(), loginRequest.getPassword()));

**Comment by SaiUpadhyayula** [comment]
Sorry for the late reply, I just tested it, works as expected. I believe you may have already found out the reason for the error by now. Let me know if you still need any help.
