### ISSUE TITLE
Mapping user comment

### ISSUE THREAD

**Issue by RafaelPuerta** [SaiUpadhyayula/spring-reddit-clone#3]
In the comment mapping add the user because the user id I was commenting on was not storing in the database

in my case just add @Mapping(target = "user", source = "user")

**Comment by SaiUpadhyayula** [comment]
Hi,

Thank you for pointing out, I managed multiple versions of the source code while developing the tutorials, and I just realized, the repository is not up to date.

I updated the source code now
