### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by LaBura** [SaiUpadhyayula/spring-reddit-clone#6]
'post.getUser()' should be 'authService.getCurrentUser()'
or you are gonna get a null pointer exception.
and thanks for the tutorial.
https://github.com/SaiUpadhyayula/spring-reddit-clone/blob/ebbdb5eab3bad8de69d8ac50342fd7ac6e50d7b7/src/main/java/com/programming/techie/springredditclone/service/CommentService.java#L39-L40

**Comment by Ghevi** [comment]
Thanks that solved it! One last issue i have is when i try to upvote or downvote. I get a nullpointerException in voteService
`if (UPVOTE.equals(voteDto.getVoteType())) {
            post.setVoteCount(post.getVoteCount() + 1);
        } else {
            post.setVoteCount(post.getVoteCount() - 1);
        }`

**Comment by mohdarif8299** [comment]
Can I work on this issue?

**Comment by SaiUpadhyayula** [comment]
Just saw the issue. @mohdarif8299  Sure, please raise a Pull Request

**Comment by mohdarif8299** [comment]
Raised a pull request! Thank you.

**Comment by SaiUpadhyayula** [comment]
Thanks for working on it @mohdarif8299
